#!/usr/bin/env python3
"""SHADOW PILOT (owner decision D1, 09.10–16.10.2026): deterministic takeover brief + task read planner.

NOT CANONICAL. Takeover still follows the full NEW-CHAT-HANDOFF.md procedure; this
file only measures whether a derived brief would be sufficient (see TZ2 report
AI-Film-Optimization-Design-2026-10-09.md on Drive). Output: shadow/.

The brief is a *navigator/cache*, never authority. It is generated by code only
(no model summarisation): verbatim current checkpoint, hashes of every source,
a rule index with anchors into the full canonical docs, a scene index of the
master, runtime freshness, and minimal read sets per task type with explicit
full-read fallback triggers.

  python3 scripts/build_takeover_brief.py [repo] [out_dir]   (defaults: . shadow)
"""
import hashlib, json, re, sys
from datetime import datetime, timezone
from pathlib import Path

GEN_VERSION = "pilot-1.0"
DOCS = {
    "NEW-CHAT-HANDOFF.md": "1lRLQZkxo6Kh6MDx8StS_c5M8cjfHDxnD",
    "SYNC-RUNBOOK.md": "1l7xXu9RDqffwJeLsc3UoPrVnx0HEdne4",
    "AI-PROJECT-GUIDE.md": "1fwklz2CLoCBDpGnGyaPfiPnEqlKz8Q2u",
    "PROMPT-STYLE-GUIDE.md": "14VzE8DwjKIquGJWENci6rYWj_1xEn34d",
    "USER-GUIDE.md": "1rEmigK5FEznmzo9g3yANlXRwNiPRwvbO",
    "README-AI-SYNC.md": "1hYMZ14esluB-kucasD6LjHWb_cBW_3wX",
    "BACKUP-AI-RUNBOOK.md": "1WwKoxhC7tGNG9xy-I7OduKYZBhVH0Ss1",
}
MASTER = ("video-prompts.md", "1yoUVfEAumOClvlBg8prFIX_BFFfoCZqj")
RECENT_DAYS = 7
HISTORY_MARKER = re.compile(r"^## Предыдущая история", re.M)
CURRENT_POINTER = re.compile(r"^## ТЕКУЩЕЕ ДОПОЛНЕНИЕ", re.M)

# Mandatory invariants: always in the brief, each anchored to the section that owns it.
# anchor = regex for a heading in owner doc; keywords = words that must occur in that section
INVARIANTS = [
    ("INV-AUTH", "Drive = editable master + 7 canonical docs; GitHub = mirror/status/site; Topview = telemetry; Notion = story/pointer; Library = recovery cache.",
     "AI-PROJECT-GUIDE.md", r"^## 2\. Источники истины", ["Drive", "GitHub"]),
    ("INV-ONE-MASTER", "One SAME-ID master; no v2/final/copy.", "AI-PROJECT-GUIDE.md", r"^## 3\. Master", ["master"]),
    ("INV-FRESH-WRITE", "Before any master write: second fresh read of the exact Drive master; minimal same-ID edit → SYNC-TRIGGER → validation → mirror/status → Pages → verification.",
     "SYNC-RUNBOOK.md", r"^## 1\. Обязательный preflight", ["fresh"]),
    ("INV-SERIAL-DOCS", "Canonical instruction writes are serial: fresh read/version → same-ID write → read-back → exact mirror → verify; never replay a stale write.",
     "SYNC-RUNBOOK.md", r"^### 8\. Serialized canonical instruction writes", ["read-back"]),
    ("INV-SCENE-ID", "Scene IDs stable; retired IDs never reused; rerender keeps the same Scene ID.", "AI-PROJECT-GUIDE.md", r"^## 3\. Master", ["Scene"]),
    ("INV-SUCCESS-NOT-APPROVAL", "Topview technical success ≠ editorial approval; never auto approve/rerun/delete/close.",
     "SYNC-RUNBOOK.md", r"^## 10\. Topview telemetry", ["approval"]),
    ("INV-SLOTS", "Slot capacity 6; one active task = one slot; Scene stays slow until its last active task is terminal.",
     "SYNC-RUNBOOK.md", r"^### Точное ТЗ — Topview slow slots", ["6"]),
    ("INV-ONE-MONITOR", "Exactly one automation «AI Film — единый монитор» (ID 6aac794245e481919ee7155c461cc77e, HH:00 MSK); archived 6aac3e4d…/6ac358bf… stay off; no duplicates; never disable it. If found disabled without an explicit owner decision to stop it: re-enable THAT task (is_enabled:true), record the incident, then verify a real publication (fresh topview-status/checkpoint + Pages). A disabled task cannot re-enable itself.",
     "SYNC-RUNBOOK.md", r"^## Действующее расписание", ["единый монитор"]),
    ("INV-NO-FAKE-TIME", "Never fake checked_at/queue/ETA; partial phases keep last confirmed timestamps.", "SYNC-RUNBOOK.md", r"^### 5\. Background connector degradation", ["checked_at"]),
    ("INV-OWNER-BOUNDARY", "Owner decides only creative/editorial choices, ambiguous task↔Scene mapping, approval, rerender, deletion/closing; deterministic work is done by the agent; never ask for info already in sources.",
     "AI-PROJECT-GUIDE.md", r"^## 14\. Поведение нового сменщика", ["пользовател"]),
    ("INV-PROMPT-AUTONOMY", "Every copyable prompt is self-contained: identity lock, reference roles/priority, camera/space, timeline, native audio, negatives, FRAME FILL.",
     "PROMPT-STYLE-GUIDE.md", r"^## 16A\. Автономность", ["prompt"]),
    ("INV-MATERIAL-CHANGE", "Material workflow/site/authority/recovery change → relevant canonical docs + SAME handoff → mirrors → 7/7 certificate → Notion pointer → Library (best-effort).",
     "SYNC-RUNBOOK.md", r"^## 9\. Material Change Documentation Rule", ["handoff"]),
    ("INV-NO-CREDITS", "No paid generation or credit spending without the canonical workflow and owner permission; launches only on owner command.",
     "SYNC-RUNBOOK.md", r"^## Scene Reference Pack automation", ["credit"]),
    ("INV-LIBRARY-NONBLOCKING", "Library is best-effort, never a completion gate.", "SYNC-RUNBOOK.md", r"^## LIBRARY RECOVERY", ["Library"]),
    ("INV-DONE", "Never say «готово» before the relevant read-back/verification passed.", "SYNC-RUNBOOK.md", r"^## 15\. Verification before final answer", ["verif"]),
]

# Minimal read sets per task, on top of the brief. 'full' = whole file.
READ_SETS = {
    "takeover": {"always": ["brief", "current_checkpoint_verbatim"], "docs": {}, "master": "index_only",
                 "note": "Shadow only. Production takeover remains the full 7+master+status read until the owner decides."},
    "prompt_edit": {"docs": {"PROMPT-STYLE-GUIDE.md": "full"}, "master": "target_scene_full + neighbours_full",
                    "extra": ["character-references.json (target identities)"]},
    "new_scene": {"docs": {"PROMPT-STYLE-GUIDE.md": "full", "SYNC-RUNBOOK.md": [r"^## 4\. Routine: добавить новую scene", r"^## 19\. Topview task intake"]},
                  "master": "last_two_scenes_full + header", "extra": ["character-references.json"]},
    "story_edit": {"docs": {}, "master": "relevant_scenes_full", "extra": ["film-analysis.md", "film-backlog.md", "montage v2", "Notion «Кино»"]},
    "topview_check": {"docs": {"SYNC-RUNBOOK.md": [r"^### Порядок фаз единого монитора", r"^### Точное ТЗ — Topview slow slots", r"^### Hourly publish gate"]},
                      "master": "none_unless_slow_change", "extra": ["topview-status.json", "topview-task-map.json", "topview-checkpoint.json"]},
    "instruction_change": {"docs": "ALL_FULL", "master": "none", "note": "material change: full current cycle"},
    "recovery": {"docs": "ALL_FULL", "master": "full", "note": "always full"},
}
FULL_FALLBACK_TRIGGERS = [
    "any source sha256 in the brief ≠ live mirror / instruction certificate",
    "instruction-sync health ≠ ok or certificate older than its freshness limit",
    "project-status health ≠ ok or canonical_master_sha256 ≠ brief master sha",
    "task touches authority, sync, recovery, schedule, slot semantics or ≥2 scenes' shared rules",
    "agent cannot answer a mandatory takeover question from the brief + read set",
    "brief generator version or schema unknown",
]


def sha(b):
    return hashlib.sha256(b).hexdigest()


def section(text, anchor_re):
    m = re.search(anchor_re, text, re.M)
    if not m:
        return None
    level = len(re.match(r"#+", text[m.start():]).group(0))
    nxt = re.compile(r"^#{1,%d} " % level, re.M).search(text, m.end())
    return text[m.start(): nxt.start() if nxt else len(text)]


def main(repo, out):
    repo, out = Path(repo), Path(out)
    out.mkdir(parents=True, exist_ok=True)
    texts, sources = {}, []
    for name, did in list(DOCS.items()) + [MASTER]:
        b = (repo / name).read_bytes()
        texts[name] = b.decode("utf-8-sig").replace("\r\n", "\n")
        sources.append({"file": name, "drive_id": did, "sha256": sha(b), "bytes": len(b)})
    js = lambda f: json.loads((repo / f).read_text(encoding="utf-8-sig"))
    ps, tv, isc = js("project-status.json"), js("topview-status.json"), js("instruction-sync-status.json")
    try:
        mon = js("automation-monitor-status.json")
    except Exception:
        mon = {}

    # validity: brief agrees with the certificate and project status at generation time
    cert = {k: v.get("drive_sha256") for k, v in (isc.get("files") or {}).items()}
    mismatches = [s["file"] for s in sources if s["file"] in cert and cert[s["file"]] != s["sha256"]]
    master_sha = next(s["sha256"] for s in sources if s["file"] == MASTER[0])
    valid = not mismatches and ps.get("canonical_master_sha256") == master_sha and ps.get("health") == "ok"

    # current checkpoint: verbatim text above the history marker + any ТЕКУЩЕЕ pointer sections
    h = texts["NEW-CHAT-HANDOFF.md"]
    m = HISTORY_MARKER.search(h)
    current = h[: m.start()] if m else h[:20000]
    # Sections below the history marker that are still in force: every '## ' section whose heading
    # carries a date within RECENT_DAYS of the newest dated heading, or that is marked 'Действующ'.
    recent = []
    if m:
        hist = h[m.start():]
        hs = list(re.finditer(r"^## [^\n]*", hist, re.M))
        def hdate(t):
            x = re.search(r"(\d{2})\.(\d{2})\.(20\d{2})", t) or re.search(r"(20\d{2})-(\d{2})-(\d{2})", t)
            if not x:
                return None
            a, b, c = x.groups()
            return datetime(int(c), int(b), int(a)) if len(a) == 2 else datetime(int(a), int(b), int(c))
        dates = [d for d in (hdate(x.group(0)) for x in hs) if d]
        newest = max(dates) if dates else None
        for i, x in enumerate(hs):
            body = hist[x.start(): hs[i + 1].start() if i + 1 < len(hs) else len(hist)]
            d = hdate(x.group(0))
            if re.search(r"Действующ", x.group(0)) or (d and newest and (newest - d).days <= RECENT_DAYS):
                recent.append(body)
    current_full = current + ("\n\n<!-- brief: recent sections below the history marker, verbatim -->\n\n" + "\n".join(recent) if recent else "")

    # invariants with anchor verification
    inv = []
    for iid, txt, doc, anchor, kws in INVARIANTS:
        sec = section(texts[doc], anchor)
        ok = sec is not None and all(k.lower() in sec.lower() for k in kws)
        inv.append({"id": iid, "rule": txt, "owner_doc": doc, "anchor": anchor, "anchor_ok": ok,
                    "section_sha256_12": sha(sec.encode())[:12] if sec else None})

    # scene index from master
    mt = texts[MASTER[0]]
    heads = list(re.finditer(r"^## Сцена (\d+) — ([^\n]+)", mt, re.M))
    scenes = []
    for i, hm in enumerate(heads):
        st, en = hm.start(), heads[i + 1].start() if i + 1 < len(heads) else len(mt)
        block = mt[st:en]
        meta = (ps.get("scene_meta") or {}).get(hm.group(1), {})
        refs = sorted(set(re.findall(r"@Image\d+", block)), key=lambda x: int(x[6:]))
        scenes.append({"id": int(hm.group(1)), "title": hm.group(2).strip(), "target_engine": meta.get("target_engine"),
                       "state": meta.get("production_state"), "render_state": meta.get("render_state"),
                       "duration_s": meta.get("duration_s"), "dialogue": (meta.get("dialogue") or {}).get("language"),
                       "depends_on": [d.get("scene") for d in meta.get("dependencies", [])],
                       "prompts": block.count("```") // 2, "refs": refs, "offset": st, "chars": en - st,
                       "sha256_12": sha(block.encode())[:12]})

    runtime = {
        "project_health": ps.get("health"), "scenes": ps.get("scenes"), "prompt_texts": ps.get("prompt_texts"),
        "scene_ids": ps.get("scene_ids"), "latest_scene": ps.get("latest_scene"), "reserved": ps.get("reserved_scene_ids"),
        "live_files": ["project-status.json", "topview-status.json", "instruction-sync-status.json", "automation-monitor-status.json"],
        "freshness_rule": "Slots, slow, ETA and monitor state: read the live JSON. checked_at older than 2 h, missing or in the future = unverified.",
    }
    brief = {"schema_version": 1, "generator": GEN_VERSION,
             "status": "SHADOW PILOT 09.10–16.10.2026 — NOT CANONICAL — do not use instead of the full takeover; fresh Drive canon always wins",
             "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
             "valid_at_generation": valid, "validity_mismatches": mismatches,
             "authority": "Drive canon/master → GitHub mirrors/status/Pages → Topview telemetry → Notion story/pointer → Library cache",
             "sources": sources, "invariants": inv, "current_checkpoint": {"source": "NEW-CHAT-HANDOFF.md",
             "chars": len(current_full), "above_marker_chars": len(current), "recent_sections_below_marker": [r.splitlines()[0] for r in recent], "sha256_12": sha(current_full.encode())[:12],
             "extra_current_sections": [x.group(0) for x in CURRENT_POINTER.finditer(h)]},
             "runtime": runtime, "scene_index": scenes, "read_sets": READ_SETS,
             "full_fallback_triggers": FULL_FALLBACK_TRIGGERS}
    def put(path, text):
        old = path.read_text(encoding="utf-8") if path.exists() else None
        strip = lambda t: re.sub(r"(\"generated_at\": \"[^\"]*\"|Сгенерирован [^ .]+)", "", t or "")
        if old is None or strip(old) != strip(text):
            path.write_text(text, encoding="utf-8")
            return True
        return False
    changed = put(out / "takeover-brief.json", json.dumps(brief, ensure_ascii=False, indent=1) + "\n")
    changed |= put(out / "current-checkpoint.md", current_full)
    # compact markdown rendering (what a chat would read first)
    L = [f"# AI Film — takeover brief ({GEN_VERSION}) — ПИЛОТ 09.10–16.10, НЕ КАНОН", "", "> Приёмка смены по-прежнему — полное чтение по NEW-CHAT-HANDOFF.md. Этот файл только измеряет, хватило бы brief.", "",
         f"Сгенерирован {brief['generated_at']}. Валиден при генерации: **{valid}**" + (f" (расхождения: {mismatches})" if mismatches else ""),
         "Brief — навигатор. При любом триггере ниже — полный fresh-read канона.", "", "## Authority", brief["authority"], "",
         "## Источники (sha256)"] + [f"- {s['file']} · Drive `{s['drive_id']}` · {s['bytes']} B · `{s['sha256'][:16]}`" for s in sources] + [
         "", "## Обязательные инварианты"] + [f"- **{i['id']}** — {i['rule']} → `{i['owner_doc']}` {'✓' if i['anchor_ok'] else '✕ ANCHOR MISSING'}" for i in inv] + [
         "", "## Runtime", f"- health {runtime['project_health']}; сцен {runtime['scenes']} ({runtime['scene_ids']}); промтов {runtime['prompt_texts']}; последний ID {runtime['latest_scene']}; зарезервированы {runtime['reserved']}",
         "- Слоты, slow, ETA, монитор — только из живых " + ", ".join(runtime["live_files"]) + ". " + runtime["freshness_rule"]] + [
         "", "## Индекс сцен", "| ID | Название | Промт-движок | Состояние | Промтов | Refs | Зависит | sha |", "|---|---|---|---|---|---|---|---|"] + [
         f"| {s['id']} | {s['title'][:60]} | {s['target_engine']} | {s['state']}/{s['render_state']} | {s['prompts']} | {' '.join(s['refs'])} | {s['depends_on']} | {s['sha256_12']} |" for s in scenes] + [
         "", "## Полный fresh-read обязателен, если"] + [f"- {t}" for t in FULL_FALLBACK_TRIGGERS] + [
         "", "## Текущий checkpoint (дословно из NEW-CHAT-HANDOFF.md, до пометки «Предыдущая история»)", "", "См. `current-checkpoint.md` "
         f"({len(current_full)} симв., sha `{brief['current_checkpoint']['sha256_12']}`)." + (" Дополнительно действующие разделы: " + "; ".join(brief['current_checkpoint']['extra_current_sections']) if brief['current_checkpoint']['extra_current_sections'] else "")]
    changed |= put(out / "takeover-brief.md", "\n".join(L) + "\n")
    print(json.dumps({"changed": changed, "valid": valid, "mismatches": mismatches, "anchors_ok": sum(i["anchor_ok"] for i in inv), "anchors": len(inv),
                      "brief_md_bytes": (out / "takeover-brief.md").stat().st_size,
                      "brief_json_bytes": (out / "takeover-brief.json").stat().st_size,
                      "checkpoint_bytes": (out / "current-checkpoint.md").stat().st_size, "scenes": len(scenes)}, ensure_ascii=False))
    for i in inv:
        if not i["anchor_ok"]:
            print("ANCHOR FAIL", i["id"], i["owner_doc"], i["anchor"])


if __name__ == "__main__":
    args = sys.argv[1:] + [".", "shadow"][len(sys.argv[1:]):]
    main(args[0], args[1])
